#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./scripts/bootstrap-backend.sh <subscription_id>
#
# Example:
#   ./scripts/bootstrap-backend.sh 00000000-0000-0000-0000-000000000000

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${SCRIPT_DIR}/backend.conf"


SUBSCRIPTION_ID="${1:?Usage: $0 <subscription_id>}"


az account set --subscription "$SUBSCRIPTION_ID"

CURRENT_USER_OBJECT_ID="$(az ad signed-in-user show --query id -o tsv | tr -d '\r')"
CURRENT_USER_UPN="$(az account show --query user.name -o tsv | tr -d '\r')"

SCOPE="/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}/providers/Microsoft.Storage/storageAccounts/${STORAGE_ACCOUNT_NAME}"
RG_EXISTS="$(az group exists --name "$RESOURCE_GROUP_NAME" -o tsv | tr -d '\r')"

if [ "$RG_EXISTS" = "true" ]; then
  echo "Resource Group already exists: $RESOURCE_GROUP_NAME"
else
  az group create \
    --name "$RESOURCE_GROUP_NAME" \
    --location "$LOCATION" \
    --only-show-errors
  echo "Resource Group created: $RESOURCE_GROUP_NAME"
fi

if az storage account show \
    --name "$STORAGE_ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP_NAME" \
    --only-show-errors >/dev/null 2>&1; then
  echo "Storage Account already exists: $STORAGE_ACCOUNT_NAME"
else
  az storage account create \
    --name "$STORAGE_ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP_NAME" \
    --location "$LOCATION" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --https-only true \
    --min-tls-version TLS1_2 \
    --allow-blob-public-access false \
    --only-show-errors
  echo "Storage Account created: $STORAGE_ACCOUNT_NAME"
fi

echo "==> Assigning Storage Blob Data Contributor role to current user"
ROLE_NAME="Storage Blob Data Contributor"

ROLE_EXISTS="$(az role assignment list \
  --assignee-object-id "$CURRENT_USER_OBJECT_ID" \
  --scope "$SCOPE" \
  --query "[?roleDefinitionName=='${ROLE_NAME}'] | length(@)" \
  -o tsv | tr -d '\r' | xargs)"

if [ "${ROLE_EXISTS:-0}" = "0" ]; then
  echo "Assigning RBAC role: $ROLE_NAME"
  az role assignment create \
    --assignee-object-id "$CURRENT_USER_OBJECT_ID" \
    --assignee-principal-type User \
    --role "$ROLE_NAME" \
    --scope "$SCOPE" \
    --only-show-errors \
    --output none
else
  echo "Role already assigned to current user"
fi

if az storage container exists \
    --name "$CONTAINER_NAME" \
    --account-name "$STORAGE_ACCOUNT_NAME" \
    --auth-mode login \
    --query exists -o tsv | grep -q true; then
  echo "Container already exists : $CONTAINER_NAME"
else
  az storage container create \
    --name "$CONTAINER_NAME" \
    --account-name "$STORAGE_ACCOUNT_NAME" \
    --auth-mode login \
    --only-show-errors
  echo "Storage Container created : $CONTAINER_NAME"
fi

# Generate backend configuration for local development.
# `use_cli = true` allows Terraform to authenticate using the active Azure CLI session
# from `az login`, which is suitable for local development.
# In CI/CD pipelines this should be replaced by service principal or OIDC-based auth.
mkdir -p "${INFRA_DIR}/environments/dev"
cat > "${INFRA_DIR}/environments/dev/backend.hcl" <<EOF
# Auto-generated by scripts/bootstrap-backend.sh
# Do not edit manually.
resource_group_name  = "${RESOURCE_GROUP_NAME}"
storage_account_name = "${STORAGE_ACCOUNT_NAME}"
container_name       = "${CONTAINER_NAME}"
key                  = "${STATE_KEY}"
use_azuread_auth     = true
use_cli              = true
EOF

cat <<EOF

Bootstrap completed.

Resource Group:   ${RESOURCE_GROUP_NAME}
Storage Account:  ${STORAGE_ACCOUNT_NAME}
Container:        ${CONTAINER_NAME}
Azure User:       ${CURRENT_USER_UPN}

Next step:
  terraform init -reconfigure "-backend-config=./environments/dev/backend.hcl"

Note:
  If it fails due to permissions, wait 1-5 minutes for RBAC propagation and retry.

EOF
