RESOURCE_GROUP="rg-tfm-ucm-g2-dev"
LOCATION="swedencentral"

LOG_ANALYTICS_NAME="log-tfm-ucm-g2-dev"
APP_INSIGHTS_NAME="appi-tfm-ucm-g2-dev"

RETENTION_DAYS=30

TAGS="environment=dev project=tfm-ucm-g2 managed-by=manual"
