RESOURCE_GROUP="rg-tfm-ucm-g2-dev"
LOCATION="swedencentral"
OPENAI_NAME="oai-tfm-ucm-g2-dev"

GPT4O_DEPLOYMENT="gpt-4o"
GPT4O_MODEL="gpt-4o"
GPT4O_VERSION="2024-11-20"
GPT4O_CAPACITY=10

EMBEDDING_DEPLOYMENT="text-embedding-3-small"
EMBEDDING_MODEL="text-embedding-3-small"
EMBEDDING_VERSION="1"
EMBEDDING_CAPACITY=10

TAGS="environment=dev project=tfm-ucm-g2 managed-by=terraform"
